name: fluzz
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # 状态管理
  provider: ^4.3.2+2
  # 缓存图片
  extended_image: ^1.1.1
  # 吐司
  oktoast: ^2.3.2
  # 本地存储
  shared_preferences: ^0.5.10
  # 模拟数据
  dart_mock: ^1.0.1+1
  # 序列化
  json_annotation: ^3.0.1
  # svg
  flutter_svg: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.4.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: fluzz
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf

flutter_intl:
  enabled: true
