name: fluzz
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 状态管理
  get: ^4.1.4
  # 缓存图片
  extended_image: ^4.0.1
  # 模拟数据
  dart_mock: ^2.0.0
  # 吐司
  oktoast: ^3.0.0
  # 本地存储
  shared_preferences: ^2.0.5
  # 序列化注解
  json_annotation: ^4.0.1
  # svg
  flutter_svg: ^0.21.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 构建工具
  build_runner: ^1.12.2
  # 序列化工具
  json_serializable: ^4.1.0
  # 开屏
  flutter_native_splash: ^1.1.7+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: fluzz
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/ic_fluzz.png